### ISSUE TITLE
Feature Suggestion: Remove 

### ISSUE THREAD

**Issue by jaredgrady** [CreaturePhil/eosdb#1]
It'd be nice if the db had an easy way to delete entries. db().remove would be a solid addition to the api.

**Comment by sparkychild** [comment]
Maybe doing db().delete(key) would be better, keeping the same set of prototypes as new Map().  Makes the API easier to pick up :3

**Comment by CreaturePhil** [comment]
https://github.com/CreaturePhil/origindb/commit/29d4403aa0a14ad7af183b05804ce604e809488b
